apiVersion: v1
kind: Service
metadata:
  name: external-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-proxy-protocol: v1
spec:
  selector:
    app: external-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: "TCP"
  type: LoadBalancer
